### ISSUE TITLE
Support custom table names

### ISSUE THREAD

**Issue by sasokovacic** [laravel/cashier-stripe#1063]
Table names should be configurable so we can prefix them or just use custom names

**Comment by driesvints** [comment]
No plans for this.

**Comment by sasokovacic** [comment]
@driesvints what a "great" response... no explanation, just shutdown. thanks ;)

**Comment by driesvints** [comment]
You can already overwrite the current migrations if you want: https://laravel.com/docs/8.x/billing#database-migrations

But changing the table names will conflict with the existing Eloquent models. That makes it hard to introduce custom table names. In general we don't want to support this because most use cases don't need custom table support and introducing this for a small minority just brings on an unnecessary maintenance burdon on us.

**Comment by sasokovacic** [comment]
What about a configurable Subscription model? You already support a custom billable model. If I can set my own model in the configuration, then I'm able to make a new Subscription model that extends yours and set a new table name directly in it. Then I just overwrite your migrations and I'm done.
Correct me if I'm wrong but the only thing on your part, in this case, is you have to add a new line in the config file and use it in the subscriptions method in the Billable trait. But maybe I'm wrong.

**Comment by driesvints** [comment]
Well actually, adding model swapping in the same fashion as Passport & Sanctum isn't a bad idea at all. I've just sent in a PR to do just that: https://github.com/laravel/cashier-stripe/pull/1067

**Comment by sasokovacic** [comment]
Great. That was fast. Thanks. Have a great day :)

**Comment by driesvints** [comment]
No worries. Sorry if I was a bit terse at first. Thanks for bringing this up 👍
