### ISSUE TITLE
Dynamically get a price from Stripe using it lookup key

### ISSUE THREAD

**Issue by laugre** [laravel/cashier-stripe#1236]
Hi there,

I just found a very interesting trick to [get a registered price from Stripe using it lookup key](https://stripe.com/docs/billing/prices-guide#managing-prices).

Any chance to get this kind of feature in Cashier ? Or Cashier not really made for that and use Stripe API instead.

Thank you for your reply.

**Comment by driesvints** [comment]
What would your main use case be to retrieve the prices?

**Comment by laugre** [comment]
In my use case, price ids are hardcoded in my back end in order to be passed when I create subscriptions.
```/*
    |--------------------------------------------------------------------------
    | Stripe Plan Prices
    |--------------------------------------------------------------------------
    |
    | These settings define ids of the stripe option pack prices
    |
    */
    'options' => [
        // family
        [
            // option 1
            [
                'price_1JNi3CHIJqAU6o1FjDrvB6JC', // monthly
                'price_1JNi3CHIJqAU6o1FmdharLLi', // yearly
            ],
            // option 2
            [
                'price_1JNi1hHIJqAU6o1FvhTn4Rs8',
                'price_1JNi1hHIJqAU6o1Fa3pFCgiR',
            ],
            // option 3
            [
                'price_1JNi5qHIJqAU6o1FLJHFt5xO',
                'price_1JNi5qHIJqAU6o1F2IgQakLm',
            ]
        ],
       ...
    ],
```
If I  change prices in Stripe I must rewrite these values. 
Idea is to init these values with price lookup keys Stripe feature.
Then I get price ids (and other price infos (amount, cycle ...)) by dynamically requesting Stripe with lookup keys
     
... a super option would then be to call 
```
$request->user()->newSubscription(
 'default', 'family_option1_monthly'
)
```

**Comment by driesvints** [comment]
I'm sorry but I don't think this is something we'll be supporting. I don't want to put in too much overhead for just this feature.

**Comment by zmorris** [comment]
@driesvints finding subscriptions and other items by `lookup_key` (or other metadata) is the very first use case I'm considering as I build out my first Stripe integration. Here is my thought process:

1. Find Stripe item by `lookup_key` (or other metadata) and create a reference to avoid hardcoding `item_abc123` ids in our database and/or code.
2. No mention of `search`, `find`, `field`, `key`, `look up`, `lookup` or `lookup_key` at https://laravel.com/docs/10.x/billing although `metadata` is mentioned for creating subscriptions (not searching them).

I spent an hour trying to figure this out and finally found:

https://laracasts.com/discuss/channels/laravel/search-try-stripe-transaction

```
$stripe = new StripeClient($my_stripe_key);
$stripe->subscriptions->search(['query' => "metadata['lookup_key']: '$my_lookup_key'"]);
```

There are 2 major problems with this:

1. The above is not Cashier code.
3. The user has to deal with security concerns like escaping values used to build search queries.

Now the questions become:

1. Can we access Cashier's underlying StripeClient class to run our own search queries?
2. If yes, then why would we use Cashier?
4. If no, then why would Cashier not support something as basic as search queries?
5. Is Cashier now suspect as a viable package for performing basic uses cases like this?
6. Why would we developers invest in learning Cashier if it can't perform basic use cases like this, especially when Stripe already has a fairly well-implemented API?

It may be possible to access the underlying StripeClient class:

https://github.com/laravel/cashier-stripe/issues?q=is%3Aissue+StripeClient
https://github.com/laravel/cashier-stripe/issues/1559
https://laracasts.com/discuss/channels/laravel/laravel-cashier-subscription-object

In the future when you're replying to issues, and fixes won't be implemented, can you provide alternatives? My thought process is:

1. The user may not be experienced enough to know a workaround that you know about, so you could save them and the rest of us a lot of time by suggesting one.
2. There may be no workaround, indicating a conceptual flaw in Cashier (or any package).

Dismissing concerns out of hand and unilaterally closing issues creates a disincentive for users to adopt your software.

Apologies if my tone here is a little harsh, but this friction comprises the majority of what I do now. My workflow nearly always looks like:

1. Initial excitement at finding a package supporting my use case(s).
2. Discovering that package is missing a critical (usually obvious) use case.
3. Having to learn nearly the entirety of the package to implement a workaround by overriding a class, service, etc.
4. Realizing that the package didn't do very much in the end, and that I could have implemented my use case(s) faster myself.
5. Rinse, repeat.

Admittedly, this may be a problem with my approach. I'm very open to approaches which I hadn't considered. But in my experience, alternative approaches usually don't exist, which forces me to do everything myself or abandon the simple course of action I was planning in favor of a less conceptually-clean approach.

In this case, if Cashier wants me to hardcode ids in database/config/.env, then the documentation should say so. Which is less than ideal, for the reasons that [laugre](https://github.com/laugre) and I mentioned. I'd vote for Cashier to implement a `query()` method to look up any item via metadata OR if a `query()` method already exists, add it to the documentation with examples. Otherwise so far it's not looking like I can endorse Cashier, and its roughly 700 issues don't inspire confidence either. But I really want to love it, so hopefully I just missed something really obvious.

Thanks otherwise for the work you do supporting Cashier and other projects!
