### ISSUE TITLE
Creating subscription with a payment_method will update the Customer default payment method in Stripe

### ISSUE THREAD

**Issue by shaifulborhan** [laravel/cashier-stripe#1247]
- Cashier Version: 13.5.1
- Laravel Version: 8.52
- PHP Version: 7.4
- Database Driver & Version:

### Description:

When creating new subscriptions using [newSubscription()](https://laravel.com/docs/8.x/billing#creating-subscriptions) and passing a payment method ID, it appears that the customer record in Stripe will be updated with the new default payment method when the customer already has an existing default payment method. Is this the intended outcome? Is there a way to prevent this behavior?

Thank you.

**Comment by driesvints** [comment]
This is the expected behavior yes. The latest used payment method will always be set as the default one. It's been like that ever since Cashier Stripe was first released. I can however see that's not wanted in some situations. You can circumvent this with:

```php
$user->newSubscription('default', 'price_xxx')->add([], ['default_payment_method' => $paymentMethodID]);
```

Also see https://stripe.com/docs/api/subscriptions/create#create_subscription-default_payment_method

One thing that's important here is that the payment method is already associated with the user.
