### ISSUE TITLE
Unable to process charges for customers with default credit card having payment ID in the form of pm_xxx, since upgrading to Laravel 8

### ISSUE THREAD

**Issue by cboudreaux** [laravel/cashier-stripe#1264]
- Cashier Version: 13.5.2
- Laravel Version: 8.61.0
- PHP Version: 8.0.8

### Description:
We are unable to process charges for customers who have a default credit card on their account, where the ID of the customer's default payment method is in the form pm_XXX. For example: pm_1Jig9sFuiQHBUm2...

When I use Cashier to get the customer's default payment method, line 132 of ManagesPaymentMethods.php performs the following call:

$customer = $this->asStripeCustomer(['invoice_settings.default_payment_method']);

And invoice_settings.default_payment_method is null, for any customer whose default credit card is stored in Stripe, by Cashier, with the ID of the payment method in the format pm_xxx.

We are able to process charges for customers where the customer's default credit card was created by Cashier and has an ID in the format of card_XXX. For example: card_1Dq2XIFuiQHBU...

I've spent a couple of hours on phone and chat with Stripe, with no resolution. Below is the last email that they sent me, which seems to simply say that the Cashier package changed the way that customers are created, and the Cashier package is checking for the customer default payment methods, and that we need to stop checking for the default payment method before processing the charge, but I am unable to find any thing in Cashier documentation that explains how to do that. Cashier seems to only process charges after calling Stripe for the default payment method.

Below is the last email that I received from Stripe support. Does anyone know how I can resolve this issue and process charges for customers with default credit cards that have payment ID in the format of pm_xxx?

Thanks!

******* BEGIN EMAIL FROM STRIPE **********

As discussed you may omit the payment method when creating the Payment Intent.

You've mentioned that this issue only started on September, so I've gone ahead and reviewed the transactions you had. I can see that you've created the payment intent with payment method but there were no request to retrieve the customer. Unlike the process that you're doing now that you have to retrieve the customer and get the invoice_settings.default_payment_method to get the payment method of a customer.

Here are the two different payment intent you've sent to us before:

https://dashboard.stripe.com/logs/req_Oj46WeRIs31kOr https://dashboard.stripe.com/logs/req_KWnm1rENxYT7xq

If you notice on this logs, there's no request to get the customer payment method, but right away, you were able to include the payment method when creating the payment intent.

https://dashboard.stripe.com/logs?created%5Bgte%5D=1628485200&created%5Blte%5D=1628571599

Comparing it to your current process right now where you're retrieving the customer and expanding invoice_settings.default_payment_method before creating the payment intent.

https://dashboard.stripe.com/logs?created%5Bgte%5D=1633582800&created%5Blte%5D=1633669199&starting_after=1633652222-req_hg05kkz3LjpeQa

I'm not sure if this additional step you're doing right now is due to upgrade you have with Laravel, but it's worth checking with them and see if you can have the same workflow you had before. Although redirecting who contacts us is never ideal, as we strive to take complete ownership of your question, I want to ensure you are on the right track and getting the assistance you deserve.

I hope this gets you on the right track, but if there's anything else we can do to help, don't hesitate to reach back out.

### Steps To Reproduce:

```php
$paymentMethod = $order->user->defaultPaymentMethod();

$chargeAmount = ...

        if (! empty($paymentMethod)) {
            try {
				$order->user->charge($chargeAmount, $paymentMethod->id, [
					'description' => '...',
				]);

                $order->payment_status = 'paid';
                $order->save();

                return 'paid';
            } catch...
```

**Comment by driesvints** [comment]
> And invoice_settings.default_payment_method is null

Most likely this is due to the fact that you're upgrading from the legacy sources API to the new payment methods API. the previous `default_source` which is most likely saved to your customer (the `card_1Dq2XIFuiQHBU`) isn't automatically transferred to `invoice_settings.default_payment_method`. You'll need your customers to re-add that source card as a default payment method (`updateDefaultPaymentMethod`) if you want to use Cashier's `defaultPaymentMethod` call to retrieve it. 

The change to new payment methods API is detailed in [Cashier's upgrade guide for v10](https://github.com/laravel/cashier-stripe/blob/13.x/UPGRADE.md#cards-and-payment-methods). Which says:

> However, at the moment there isn't a way to retrieve the default source from a customer through the Payment Methods API. Therefore, the defaultPaymentMethod method on the Billable user will return an instance of a Stripe\Card or Stripe\BankAccount if no default Payment Method could be found.

Later on in Cashier v13 [we removed all support for the legacy Sources API](https://github.com/laravel/cashier-stripe/blob/13.x/UPGRADE.md#stripe-sources-support-removed). This probably causes the issues you're experiencing. I've sent in a PR to clarify further what the behavioral change to the `defaultPaymentMethod call is: https://github.com/laravel/cashier-stripe/pull/1265

Ideally, as I said to Stripe several times, I wished that the `default_source` was automatically available as `invoice_settings.default_payment_method` but it doesn't seems that Stripe is willing to do this.

There are several guides you can follow if you like: 

- https://stripe.com/docs/payments/payment-intents/migration#access-payment-methods
- https://stripe.com/docs/payments/payment-methods/transitioning

Or you can make a manual payment intent call that omits the `payment_method` parameter (which will result in `default_source` being used. However, Stripe doesn't recommends this, see https://stripe.com/docs/api/payment_intents/create#create_payment_intent-payment_method

> If this parameter is omitted with confirm=true, customer.default_source will be attached as this PaymentIntent’s payment instrument to improve the migration experience for users of the Charges API. We recommend that you explicitly provide the payment_method going forward.

Hope this clarifies things.
