### ISSUE TITLE
Discrepancy between factory and query

### ISSUE THREAD

**Issue by jasonvarga** [laravel/cashier-stripe#1278]
- Cashier Version: 13.6.0
- Laravel Version: 8.68.1
- PHP Version: 7.4

### Description:

This isn't really a bug (yet?) but maybe just a question.

I was adjusting some of my tests and app code to use the new factories and thought I could leverage the existing Cashier factories.

I noticed that the `SubscriptionFactory`'s `canceled` state just sets the `stripe_status`

https://github.com/laravel/cashier-stripe/blob/4bd3b2488cb107b5d5160f97afbc2960a28a1393/database/factories/SubscriptionFactory.php#L86-L91

But when you query for cancelled models or use the cancelled method itself, it uses the `ends_at` column.

https://github.com/laravel/cashier-stripe/blob/4bd3b2488cb107b5d5160f97afbc2960a28a1393/src/Subscription.php#L296-L299
https://github.com/laravel/cashier-stripe/blob/4bd3b2488cb107b5d5160f97afbc2960a28a1393/src/Subscription.php#L307-L310

Is there a reason this is different?

### Steps To Reproduce:

Using this quick factory creation and assertion, I'd expect it to be true.

```php
$sub = Subscription::factory()->canceled()->create();

$this->assertTrue($sub->cancelled()); // it's false.
```

### Additional Details

Also, and it's less of an issue, but you have `canceled` with one L in the factory and `cancelled` with 2 Ls in the model. Stripe uses `canceled`.

**Comment by jasonvarga** [comment]
I'm sure you know this, but I think `$subscription->cancelled()` only looks at `ends_at` for backwards compatibility for subscriptions created before the `stripe_status` column was introduced.

**Comment by driesvints** [comment]
> Is there a reason this is different?

No, this is an oversight from https://github.com/laravel/cashier-stripe/pull/1096 when they were first introduced. "cancelled" in Cashier means when an ending period has been set (even if it's in the future and not yet actually cancelled). This is to give time for a "grace period" in which the customer can still use the remaining active time. You can read more about this here: https://laravel.com/docs/8.x/billing#cancelling-subscriptions

It's not the same as "canceled" in Stripe. A "canceled" status for Stripe only is set when the subscription is actually cancelled. This is because Stripe does not consider the subscription to be cancelled when it's in its grace period. "$subscription->cancelled()" in Cashier will return `true` even when it's in its grace period. This is to determine if in fact, the subscription is cancelled or will be cancelled in the future.

Now I agree this is confusing. I'll try to do the following things:

- Clarify the above behavior in the docs
- Send in a PR to fix the factory behavior (and check the other statuses as well)
- Talk to the team to maybe bring Cashier more on par with Stripe's behavior (although it's unlikely we will as that involves breaking changes)

About the mixed usage of "cancelled" & "canceled": I agree this is confusing and I also talk to the team about maybe moving everything to "canceled" to mimic Stripe.

**Comment by jasonvarga** [comment]
Cashier's "cancelled" behavior makes perfect sense. I doubt you'll want to change that.

But maybe there could be some clearer factory states whether you're cancelling Cashier style, or it's cancelled according to Stripe. 👍 

Thanks for the detailed response!

**Comment by driesvints** [comment]
@jasonvarga I discovered that a subscriptions cancelled status is already explained in detail here: https://laravel.com/docs/8.x/billing#cancelled-subscription-status

I sent in a couple of other PR's that both should consolidate the canceled naming and fix the factory state.
