### ISSUE TITLE
Changing plans via Stripe Billing Portal

### ISSUE THREAD

**Issue by PhiloNL** [laravel/cashier-stripe#1288]
- Cashier Version: v13.6.0
- Laravel Version: 8.73.1
- PHP Version: PHP 8.0.13
- Database Driver & Version:

### Description:
I'm following up on the following issue https://github.com/laravel/cashier-stripe/issues/1035 with a demo repository.
If you have any questions or if there is anything else I can do to help, let me know 🙌 

### Steps To Reproduce:
https://github.com/PhiloNL/bug-report

**Comment by driesvints** [comment]
> You will still see 'basic' as the chosen plan because the name property is not updated in the database. All other properties like the price_id did get updated.

I think you misunderstand what the `name` property stands for. This often leads to confusion but `name` doesn't represents any value for an end user. It's solely meant as an internal representation of the "type" of subscription. 

For example, the "default" subscription is your "main" app subscription for, for example, amount of users allowed within a team while an "api" subscription could be a subscription for metered billing for API call usages. The "name" value for this subscription never changes, even when a price_id changes.

The "name" property of a subscription is explained here: https://laravel.com/docs/8.x/billing#creating-subscriptions. Did you already read this or does that make it clear? Otherwise I'll try to give it another go at updating it.

**Comment by PhiloNL** [comment]
Thanks for getting back to me, Dries 😄 

I already read the explanation for creating subscriptions, but I now see I have misunderstood based on your feedback, and I must use `subscribedToProduct` in my case.

Sorry for bothering you with this 🙏 
Have a great day!
