### ISSUE TITLE
subscribedToProduct() returns false for Subscription of multiple products.

### ISSUE THREAD

**Issue by secrethash** [laravel/cashier-stripe#1330]
- Cashier Version: 13.8.2
- Laravel Version: 8.83.0
- PHP Version: 8.1.2
- Database Driver & Version: Mariadb 10.6.5

### Description:

I have two types of Billing in my application. First is a normal Plan based billing named & accessed as  **default** in Cashier and the second is Addons or Optional Features that users can subscribe to if wanted (example: monitoring) named & accessed as **addon**. A User can subscribe to One Plan billing at a time but several Addons based billing at a time.

This results in One Active Subscription for Plan Billing per user but Several Active Subscriptions for Addons.

When calling `subscribedToProduct('prod_id', 'addon')`, it returns false even if it should be true if there are subscriptions of multiple products as it checks only the most recent subscription.

### Steps To Reproduce:

The Complete Scenario that I am using this for:

A user can be subscribed to **default** for a basic billing plan and **addon** for Plan Addons. Addons can be multiple so there are multiple subscriptions for **addon**. I can check a users basic billing plan subscription using `subscribed('default')` but to check subscription for a particular **addon** I have to be specific so I use `subscribedToProduct('prod_id', 'addon')`. But if I am subscribed to 2 addons the most recent subscribed one returns true but the previous ones return false. I believe this is because the logic for `subscribed()` and `subscribedToProduct()` is same, using `$this->subscription()` in `Laravel\Cashier\Concerns\ManagesSubscriptions`. For `subscribed()` it completely makes sense but I think `subscribedToProduct()` should be going through all the active ones under the provided name (here 'addon') instead of checking only the most recent one.

https://github.com/laravel/cashier-stripe/blob/45fec996e38c0ae6c7d6d06531a9421b7a475928/src/Concerns/ManagesSubscriptions.php#L135-L138

https://github.com/laravel/cashier-stripe/blob/45fec996e38c0ae6c7d6d06531a9421b7a475928/src/Concerns/ManagesSubscriptions.php#L98-L101

**Comment by driesvints** [comment]
Please provide a clear description and overview of all your products and prices in Stripe as well as your subscription names.

**Comment by secrethash** [comment]
I have updated the description and references. Please tell me if anything else is needed.

**Comment by driesvints** [comment]
The problem is that you're associating the `name` `addon` with several types of subscriptions. This is not possible within cashier. One name for a subscription equals one type of subscription. You'll need to use `addon-1`, `addon-2`, etc. 

More likely, you're looking for multiprice subscriptions rather than multiple subscriptions of different types. Please see https://laravel.com/docs/9.x/billing#multiprice-subscriptions

Please try a support channel if you need more help:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by secrethash** [comment]
Well, I found another solution `onProduct()` that would work for this case but is not documented.

For future reference if anyone else needs this:

https://github.com/laravel/cashier-stripe/blob/45fec996e38c0ae6c7d6d06531a9421b7a475928/src/Concerns/ManagesSubscriptions.php#L176-L187
