### ISSUE TITLE
findInvoice doesn't allow you to specify options

### ISSUE THREAD

**Issue by quantumwebco** [laravel/cashier-stripe#1487]
When using the findInvoice($id) method I would like to "expand" the payment_intent

Would you accept a PR if I added ```findInvoice($id, $options = [])``` so that we could do ```findInvoice($id, ['expand' => ['payment_intent']])``` and pass it through like ```$stripeInvoice = $this->stripe()->invoices->retrieve($id, $options);```

Happy to add this and open a PR for it

Thanks!

**Comment by driesvints** [comment]
Yeah think that's useful. Feel free to send in a PR to the master branch since this would involve breaking changes. Also please update the `findInvoiceOrFail` & `downloadInvoice` methods as well.

Please note that we currently don't have an ETA for Cashier Stripe v15. In the meantime it's best that you use the Stripe SDK directly if you need this. Thanks!
