### ISSUE TITLE
Collation not specifically set on stripe_id to correct utf8_bin

### ISSUE THREAD

**Issue by hnccox-yard** [laravel/cashier-stripe#1700]
### Cashier Stripe Version

15.4.1

### Laravel Version

11.19.0

### PHP Version

8.3.8

### Database Driver & Version

MySQL 8.2.0

### Description

When installing laravel/cashier and running the migrations, I noticed that the stripe_id column does not use the utf8_bin collation but utf8mb4_unicode_ci, even though the documentation says this is recommended by Stripe.

When searching the docs, I came across https://github.com/laravel/cashier-stripe/issues/534 which correctly says the collation for the stripe_id column. So is this a regression bug?

https://github.com/laravel/docs/pull/4625 Would have fixed this issue.

### Steps To Reproduce

Following the installation steps for Laravel Cashier, after running the migration, check the Users table stripe_id column.

**Comment by hnccox-yard** [comment]
Upon further inspection, I notice that the column isn't even unique in the database table.

Could this be confirmed as a bug or not? I'll gladly create a PR for it.

**Comment by driesvints** [comment]
We removed this again from the migrations because it wasn't compatible with other database engines. See https://github.com/laravel/cashier-stripe/issues/747

There's a note about this all in the install docs: https://laravel.com/docs/11.x/billing#installation

<img width="753" alt="Screenshot 2024-08-05 at 10 56 13" src="https://github.com/user-attachments/assets/7ec20974-aa6d-4fab-840f-4a2ee795756f">
