### ISSUE TITLE
Move stripe customer to separate model

### ISSUE THREAD

**Issue by zagreusinoz** [laravel/cashier-stripe#545]
Rather than modify an existing model (e.g. users, etc), we create a new model - StripeCustomer which can then have a polymorphic relation to any model.  Subscriptions then would be related to the StripeCustomer.  A new IsStripeCustomer trait could then implement the relation back to the StripeCustomer.

So, an Uber clone could make multiple models billable very easily, e.g. Drivers, Passengers, Companies

This would have the benefit of:
- Reduce the configuration required, just add the trait to a model and voila.  No need to modify your model, etc.
- Once the StripeCustomer is abstracted, would make it (logically) easier to add a StripeAccount trait which would do a similar thing but to support stripe custom accounts
- Makes it easier to trigger Stripe requests with queue, because you just need to queue things from StripeCustomer not from a number of different models
- Webhooks only need to reference and update one model

The downsides:
- none that I can think of, maybe a bit more complexity / challenge to maintain?

**Comment by driesvints** [comment]
Hmm, this is interested but unsure how complicated this will get. I'll ping @taylorotwell to see what he has to say.

**Comment by JexPY** [comment]
Any progress?

Thanks.

**Comment by martinbean** [comment]
I quite like the idea of this. I have two applications that are “multi-sided marketplaces”:

1. A video on demand site where my customers connect their Stripe accounts to offer subscriptions/rentals to their customers.
2. A multi-tenant CMS where my customers subscribe, but can also connect their own Stripe accounts to add e-commerce functionality to their websites.

**Comment by logan-jobzmall** [comment]
You could also create a more polymorphic approach for Billable. This could be attached to any model dynamically. For any card_last_four or stripe_id information, it could be added to the model via a console command.

**Comment by logan-jobzmall** [comment]
You could just alter the migrations after publishing them, and created an `accounts` or `customers` table, that has a polymorphic relationship to the "accountable" or "customerable" relationship (user, organization, etc.). Each `account` would have your stripe_id, card_brand, card_last_four, trial_ends_at etc.

**Comment by gerardnll** [comment]
I guess my use case would fit in this Issue. I have Users that have N shops, and each of these shops have a Subscription. User pays for those subscriptions, so he does not have a Subscription himself but shops do.

**Comment by driesvints** [comment]
@gerardnll can't you proxy those subscription calls then through the linked user in your Shop model?

**Comment by Paulsky** [comment]
@gerardnll Did you find a solution for this? I'm looking for something similar where (in this example) the shops have for example bronze, silver and gold plans. Each plan unlocks more features for the shop.

**Comment by driesvints** [comment]
I've just had a brief chat with Taylor about this and this is definitely something we can consider. However, it would probably be something we'd implement ourselves so we can have a thorough thought about how we'd like to see this implemented. When that'd be we don't know but in the meantime feel free to leave any ideas about this or provide this as a third party implementation. Thanks all.

**Comment by driesvints** [comment]
FYI: we've implemented support for this into Cashier Paddle: https://github.com/laravel/cashier-paddle/pull/18

We're considering doing this for Cashier Stripe as well maybe but the breaking change would be quite big.

**Comment by iantasker** [comment]
Has there been any progress on this? 

With the release of Spark this looks to be blocker to it offering user and team billing like the classic version did with stripe.

**Comment by driesvints** [comment]
@iantasker atm we're still holding off on this one because it would mean some very large breaking changes for anyone currently using Cashier Stripe.

We've written a cookbook for Spark in the meantime on how to use team billing with Spark Stripe: https://spark.laravel.com/docs/1.x/spark-stripe/cookbook.html#team-billing

**Comment by martinbean** [comment]
@iantasker A current workaround right now would be to create separate subscription tables for each “billable” entity you’re looking to support in your application, i.e. `subscriptions` (for users), `team_subscriptions`, etc.

You can apply the `Billable` trait to multiple models, but override what you need to in each model (i.e. the table name, specifying the foreign key in the `subscriptions` relation, etc).

**Comment by iantasker** [comment]
@driesvints Thanks for an update. 

I have read that documentation but that covers user or team billing when spark classic has both. 
If this is going to be a breaking change will a [13.x] PR be forthcoming?

**Comment by driesvints** [comment]
@iantasker no that's what I'm trying to say. The upgrade path will be pretty big. Which is why we're not considering this atm for any upcoming release. We could maybe reconsider this in the future when the time is right which is why I'm leaving this issue open for now.

**Comment by iantasker** [comment]
@driesvints I have created an extension module for cashier that will include this functionality, I hope to release it soon after some testing.
 
I can understand your hesitancy in implementing the functionality as that in-place upgrade path is going to be very tricky.

**Comment by driesvints** [comment]
We've decided to let this one go. It will only be useful for a small portion of Cashier's user base but will impact every single cashier user with a huge breaking change. So we don't feel that it'll provide the required value that warrants the breaking changes.

**Comment by LTroya** [comment]
Hi @martinbean,

> [@iantasker](https://github.com/iantasker) A current workaround right now would be to create separate subscription tables for each “billable” entity you’re looking to support in your application, i.e. `subscriptions` (for users), `team_subscriptions`, etc.
> 
> You can apply the `Billable` trait to multiple models, but override what you need to in each model (i.e. the table name, specifying the foreign key in the `subscriptions` relation, etc).

Any idea of how to get the correct model when a stripe webhoook reaches your application when using this approach?

**Comment by martinbean** [comment]
> Any idea of how to get the correct model when a stripe webhoook reaches your application when using this approach?

@LTroya I’d maybe use metadata on the subscriptions themselves to determine what billable entity they relate to.

I’ve not really had to deal with subscriptions for multiple billable entities. In my examples:

* In the video on demand marketplace, the subscriptions are created in my Stripe account. Customers subscribe via my application in a similar way to you would subscribe to multiple creators on Patreon.
* In my CMS platform, websites don’t offer subscriptions. They just offer one-off purchases, that my application then creates direct charges for. So customers appear to be transacting with the website rather than my platform. But as mentioned, these are one-off purchases, not subscriptions.

If you have the need for subscriptions for multiple billable entities, then I’d set metadata when creating the subscription:

```php
$user->newSubscription()->withMetadata([
    'owner' => $billable->getMorphKey(),
])->create();
```

You should then be able to inspect this metadata when receiving the webhook event, to fetch the correct entity, and subscription record from the appropriate table.

**Comment by niels-numbers** [comment]
> You could just alter the migrations after publishing them, and created an `accounts` or `customers` table, that has a polymorphic relationship to the "accountable" or "customerable" relationship (user, organization, etc.). Each `account` would have your stripe_id, card_brand, card_last_four, trial_ends_at etc.

+1 to @logan-jobzmall's approach - the `billing_customers` table with a polymorphic owner is the right answer. Dropping a concrete example in case it helps anyone landing here, since I went back and forth on this for a while before realising he already had it.

In my app, both `User` and `Institute` need to pay:

- A `BillingCustomer` model with its own table holds all Stripe columns and is the only model with the `Billable` trait.
- It has a polymorphic `owner` relation (`owner_id` + `owner_type`).
- A small `HasBilling` trait on the domain models exposes `morphOne(BillingCustomer::class, 'owner')` and a `billing()` accessor that lazily creates the customer on first use. Email/name come from the owner via `stripeEmail()` / `stripeName()` on `BillingCustomer` (same idea as Logan's "contactable" suggestion).

Set `CASHIER_MODEL=App\Billing\BillingCustomer`, point `subscriptions.user_id` at `billing_customers.id`, and webhooks resolve through the Stripe customer id - agnostic to whether the owner is a user, an institute, or anything else.

```php
$user->billing()->checkout([...]);
$institute->billing()->newSubscription('default', $price)->create();
```

This matches Stripe's own data model (their `Customer` is a separate entity from your app user), avoids duplicated Stripe columns, and makes guest checkouts or org-level billing trivial later. Cashier upgrades stay painless because you are on the standard path.

So I do not think Cashier needs native support for this - the existing answer in this thread is the right one.
