### ISSUE TITLE
301 Redirect on Webhook

### ISSUE THREAD

**Issue by djekl** [laravel/cashier-stripe#67]
I have setup stripe and Cashier and its all working fine. However I have recieved an email from Stripe with regards to 301 redirect issues. The url is setup as per instructions /stripe/webhook (no trailing slash). However this is the response I get when testing in the dashboard

``` html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="refresh" content="1;url=https://xboxapi.com/stripe/webhook" />

        <title>Redirecting to https://xboxapi.com/stripe/webhook</title>
    </head>
    <body>
        Redirecting to <a href="https://xboxapi.com/stripe/webhook">https://xboxapi.com/stripe/webhook</a>.
    </body>
</html>
```

**Comment by azamk100** [comment]
What was your resolution on this? I have the same problem now.

**Comment by jtrod** [comment]
I was having the same issue. It didn't have anything to do with the URL being secure nor Cashier. And this should NOT be ignored, since your webhook will be useless.  In my case, it was the VerifyCsrfToken that was misconfigured by someone else for that project, eventhough I set the 'stripe/*' in the $except property, the method inExceptArray wasn't being called. You can see the original handle method in the parent VerifyCsrfToken aliased as BaseVerifier. So make sure to have "$this->inExceptArray($request) ||" is in your If condition in your middleware

**Comment by azamk100** [comment]
Yup. I figured out shortly afterwards that I hadn’t configured the csrf
exception properly.

I’m all set now. Thank you for replying!
