### ISSUE TITLE
How about Paypal?

### ISSUE THREAD

**Issue by moazam1** [laravel/cashier-stripe#7]
It's a wonderful package @taylorotwell Can you add Paypal or Authorize.net in this package please?

**Comment by PabloRozin** [comment]
@taylorotwell I know that Strip is excellent, but I live and work in Argentina and here is obsolete, as it is in many other countries, because it doesn't work with many of our national banks and local payments solutions. Are you planing to add the posibility of using other gateways instead of Strip like Paypal?

**Comment by eduacostam** [comment]
I'm with @PabloRozin here, I'm also from Argentina and the business for which I work was using Stripe a few months ago. Stripe sent us an email telling us that because we have less than half of our customers living in the USA they had to close our account. 

The thing is, regrettably, that Stripe has a long way to go before it can be used for any businesses that has more customers outside the USA than inside the USA.
Braintree (and PayPal for that matter) do not have this limitation and work all over the globe. I think it would be great to allow cashier to use a driver model in which we can hook different providers.

I understand that this is no easy undertaking and it might be outside the scope of the package, and that's okey... Just my two cents.

**Comment by tomicakorac** [comment]
+1. Stripe is an awesome service of course. However its availability around the World is quite limited, to say the least. If @taylorotwell sees any interest in folks not residing in the few countries supported by Stripe, he should most definitely consider adding other payment processors, such as Paypal, 2checkout, Skrill etc. The way it is now, over 90% of potential Cashier users remain out of the game, which is sad.

**Comment by lucabartoli** [comment]
21 Countries out of 205? Are you serious??
Furthermore, only 9 countries are production ready by now, 8 in beta and 4 in private beta.
Really, a payment platform which accept payments only by the 10% (5% production ready) of the world is just a bit more than a college summer project.

@taylorotwell I really don't think Stripe is suitable for any global business in the world.
Maybe you've agreed to a partnership with stripe or you like stripe more than any other platform, no one will blame you for that, but please don't deny the evidence. Otherwise, why not implementing the new paypal RESTful API? What about the framework agnosticity? Can you really ignore the fact Paypal is the most widespread payment service in the world?

**Comment by tomicakorac** [comment]
@lucabartoli that isn't constructive at all from your side, is it? Please bear in mind that Github's issues are not meant to be used as a discussion forum. You should not use it to express your opinions and emotions, but rather to share useful information.

After all, both Cashier and Laravel are open source libraries, and if you are that much affected by lack of PayPal integration, there's literally nothing stopping you to build a PayPal integration library on your own and share it for the benefit of us all.

**Comment by lucabartoli** [comment]
@tomicakorac everyone in this issue expressed his opinion, referring the fact Taylor doesn't consider this as issue at all. Mainly, I followed the flow, expressing my opinion about the coverage of stripe.
We are here because we all think Cashier is an amazing component, but stripe is useless for 196 countries out of 205 worldwide (at the moment).
Can I write my own implementation? sure I can. is it the point? no.
You're free to answer, but you're right, this is not a forum, so i will not comment anymore about that. Feel free to read between the lines and catch the real meaning of my comment.
Nothing personal against you or Taylor, believe me.

**Comment by taylorotwell** [comment]
If someone wants to write a 100% cashier syntax compatible PR to support PayPal then go for it and send it over.

**Comment by tomicakorac** [comment]
> Can I write my own implementation? sure I can. is it the point? no.

Actually, that's exactly the whole point of Open Source development.

**Comment by onlymega** [comment]
The easiest way to integrate paypal in cashier is to pre-pay stripe credit using paypal express checkout.
User pays with paypal fixed amount (prepays his subscription) and this amount is added to the stripe customer (as account balance credit).

**Comment by tomicakorac** [comment]
@onlymega I'm afraid you've missed the point. Vast majority of the World's population are not allowed to have a Stripe account at all, as Stripe only operates in a very small number of countries. The problem is not paying from the buyer's side, it's funds withdrawal from the seller's side.

**Comment by onlymega** [comment]
I have two projects running on Stripe cashier library and many users simply cannot pay because their cards are declined (5-10% of transactions are failed even if user has payed firs time with the same card without any problems). It would be nice to add the prepay option using Paypal express checkout to solve such issues.

**Comment by taylorotwell** [comment]
There is about a 0.01% chance that Cashier will ever support Paypal. The
whole process of processing subscription payments on a recurring basis is a
giant leaky abstraction because each payment provider is going to be
slightly different. There isn't some PSR for subscription processing. We
can never use a library like OmniPay because it doesn't do subscription
billing, it does one-time billing, meaning you would need to write all of
your own actual recurring billing logic, refunds, cron jobs, proration,
coupons, etc.

The best chance to have something like Cashier for Paypal is just fork
Cashier or even start from scratch and write a package for subscription
billing *specifically* for Paypal. It will never be jammed into Cashier.

**Comment by TheSachin** [comment]
@taylorotwell - Hi I understand that you don't wish to integrate PayPal into Cashier. But Stripe is not as spread as PayPal.

> The whole process of processing subscription payments on a recurring basis is a giant leaky abstraction because each payment provider is going to be slightly different
I agree with that too. Can we have separate package for PayPal, or that would be too much overkill.

**Comment by kevosomi** [comment]
I stand to be corrected but what @taylorotwell is pointing out here is pretty simple, he likes to work with stripes, which is pretty opinionated but acceptable considering that Laravel and Cashier are open source. However, as the end consumers of these awesome products, we would appreciate a little guidance on how to 'hack' into cashier and bring in Paypal  or any other gateway for that purpose.

**Comment by PhillipMwaniki** [comment]
We will have to consider starting a paypal-cashier project. Taylor is going to stand his ground on this no matter what we say.

**Comment by kkomelin** [comment]
Let's look at the problem from a different angle and find a positive point. Developers have to code a little bit more in countries that are not supported by many services, which gives them experience and makes them stronger. There is not the third option, you either swim or sink.

**Comment by davco98** [comment]
So, if you're trying to startup a business outside the US, and you want to use Laravel, you have to frickin' wait until Stripe decides to enter your country.

**Comment by kkomelin** [comment]
> So, if you're trying to startup a business outside the US, and you want to use Laravel, you have to frickin' wait until Stripe decides to enter your country.

"Entrepreneurs are simply those who understand that there is little difference between obstacle and opportunity and are able to turn both to their advantage."  - Victor Kiam

**Comment by jcsoriano** [comment]
(Now almost 2018 - more than 3.5 years since this issue was closed)

I checked Paypal's PHP SDK and it seems to now support almost the same flow as Stripe and Braintree's recurring payments now (if I'm not mistaken):

https://paypal.github.io/PayPal-PHP-SDK/sample/#billing

1. Create a plan (https://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreatePlan.html)
2. Use that plan for the recurring billing (https://paypal.github.io/PayPal-PHP-SDK/sample/doc/billing/CreateBillingAgreementWithPayPal.html)

Does anyone think integrating Paypal is becoming more of a possibility now with the current state of their API? I've worked with both Stripe API and Paypal API and I'm seeing the usage of both are very similar now.

Just wondering if the door is opening for Paypal to be included to this wonderful package.

**Comment by tomicakorac** [comment]
Most of us do. However as this issue is closed and Taylor clearly has no interest in reconsidering the decision, this remains highly unlikely to happen.

**Comment by robclancy** [comment]
> So, if you're trying to startup a business outside the US, and you want to use Laravel, you have to frickin' wait until Stripe decides to enter your country.

Or you could you know... use your programmers to solve the business problems? Many people use PayPal with Laravel and other frameworks. It doesn't need official support to work.

**Comment by robclancy** [comment]
> Most of us do. However as this issue is closed and Taylor clearly has no interest in reconsidering the decision, this remains highly unlikely to happen.

If there was a PR or someone showed how apparently similar they are now I'm sure he might consider it again (consider, not do it). That said, if it is so similar it wouldn't be hard to fork and adapt?

**Comment by jcsoriano** [comment]
So I checked the source code of this repo and found that this package seems only for Stripe. I checked back at the [docs](https://laravel.com/docs/5.5/billing) and found that the Braintree implementation is an [entirely different package](https://github.com/laravel/cashier-braintree). So it seems for anyone who'd like to contribute to make Laravel Cashier Paypal a reality (developers in 150+ countries will thank you profusely!), they'd have to create something like a cashier-paypal implementation that adheres to how Taylor does it in these two packages. 

If anyone has the skill (that I don't have) to take this on, this might be a good starting point on creating subscription billing with Paypal's newer REST API (as of 2017): https://devdojo.com/blog/tutorials/using-paypal-in-your-laravel-app

I understand that anyone can make their own implementation but the way Taylor does it is just beautiful. I'm sure people from non-developed-countries would absolutely appreciate also being able to do 
```
if ($user->onTrial())
```
or 
```
$user->subscribed('main')->cancel();
```
and all of those goodness just by doing something like 
```
composer require laravel/cashier-paypal
```
like you guys in developed-countries are able to do with `laravel/cashier` and `laravel/cashier-braintree` :D

It might also make good business sense for the Laravel team to make this possible. I'm sure Laravel usage would get a big boost because devs from 150+ countries can now also integrate billing to their apps easier (let's face it, what percentage of Laravel apps don't need billing nowadays?). More Laravel usage = more users of Laravel's paid products like Forge, Spark, Envoyer, etc. (The friction experienced by developers from 150+ countries to be able to do something as fundamental as subscription billing when using Laravel might be a lost opportunity!)

**Comment by pursehouse** [comment]
Why is it called Cashier if it is hard set to only support one gateway? Shouldn't it just be laravel-stripe?

**Comment by robclancy** [comment]
Because cashier sounds way cooler.

**Comment by pursehouse** [comment]
that's really shitty though... example Spark is built to support Cashier structure. So if Cashier was a library structure as opposed to just a strict one-off tool, then people could write Cashier compatable libraries to work with the gateways they use. Instead this is just some random library for a specific company, not a functionality expansion. So every implementation of any gateway has to be rewired on both sides to be usable.

**Comment by pursehouse** [comment]
and the refusale to make that ability possible isn't much motivation for people to try to help the framework that is literally telling them it doesn't care what they need. So the solutions are all going to stay internal

**Comment by robclancy** [comment]
Nah cashier does sound way cooler and if someone made drivers for other providers well enough they would be merged.

I'd rather the framework be the focus instead of gateways which change lots, have lots of differences and already have many libraries.

You know you can also write your own code right? You don't need everyone to do it for you.

**Comment by pursehouse** [comment]
@robclancy from looking at the code, it currently has no abiltiy to support other providers. That's why the "cashier-braintree" is a totally unrelated project as opposed to an extension.

as far as...

> You know you can also write your own code right? You don't need everyone to do it for you.

you realzie the point of these public projects is so that the 4 years of people complaining about the same exact problem can be solved instead of everyone solving it themselves internally. Especially when this is tool is meant to be a selling point for a not-free package. Telling people they have to switch providers in order to use a product is not a great path.

**Comment by robclancy** [comment]
Look at the 3rd comment. Anything after that is pointless bitching like what you are doing now. All providers have libraries you can use. This one works with stripe.

**Comment by pursehouse** [comment]
well then I guess laravel shouldn't exist at all. cuz people can write their own code. Congratulations

**Comment by robclancy** [comment]
You're dumb as hell.

**Comment by pursehouse** [comment]
clearly this is a scenario where Stripe is giving kickbacks to the Laravel owner to soley support their platform. So that people will use switch to their platform and make them money. Cuz "why make things dynamic and extendable" is the absolute opposite of an engineering goal. And you already showed you don't know the codebase with your comment that another provider would be added, but already a new one is in another project by the same people. Because Cashier has no technical dynamics in it.

**Comment by robclancy** [comment]
Holy crap dumb as hell and a conspiracy theorist.

I don't need to know the codebase because I can do this thing called programming. And I could change it to support whatever I wanted.

**Comment by mikerogne** [comment]
Laravel Cashier does support Braintree... I'm confused ¯\_(ツ)_/¯

**Comment by robclancy** [comment]
You call this small thread with like 5 people community complaints? Holy moly what a small community.

**Comment by pursehouse** [comment]
@mikerogne no, another separate library called "cashier-braintree" supports braintree. They have no actual technical relation

**Comment by pursehouse** [comment]
@robclancy if your only input is "don't support things" then you serve no purpose in communal software

**Comment by mikerogne** [comment]
https://laravel.com/docs/5.5/billing#introduction

> Laravel Cashier provides an expressive, fluent interface to Stripe's and Braintree's subscription billing services. It handles almost all of the boilerplate subscription billing code you are dreading writing. In addition to basic subscription management, Cashier can handle coupons, swapping subscription, subscription "quantities", cancellation grace periods, and even generate invoice PDFs.

**Comment by mikerogne** [comment]
What does it matter if it's "separate" -- it's still a part of Laravel Cashier according to the official documentation. Why are we raising such a stink about this again?

**Comment by pursehouse** [comment]
then the docs are lying. that's super great for a technical tool. Either way the point was to have PayPal ( and really should be able to support anything via extension ), nothing to do with Braintree

**Comment by mikerogne** [comment]
Braintree is a Paypal company, and does support Paypal.

**Comment by kevosomi** [comment]
When you argue with a mad man in the streets, you start looking like one. Let common sense prevail.

**Comment by pursehouse** [comment]
pretty sure I've said the specific reason for cashier to be an extendable base 4 times in response to you, let alone my original post and every post from people before me. You have no reason to be writing on here. Do you understand what "extendable" means? You're basically just trolling to say code should not be improved and everyone should solve their own internal features in their own way. The exact opposite point of shared software

**Comment by robclancy** [comment]
Yeah but your reasons are bullshit. It's just you being self entitled.

Cashier does the exact job it set out to do and quite well. At no point does it attempt to or say it is for all providers. That's just something in you made up in your little self entitled head.

**Comment by pursehouse** [comment]
just to be clear. you're only goal is to make it so that cashier stays unable to be extended upon. Correct?

**Comment by mikerogne** [comment]
I tend to agree with @robclancy here honestly. It sounds like you're expecting Cashier to do "too much" -- even though it already *does* support what you want (Paypal ... Braintree is a Paypal company). If you're curious about fees, just look at Braintree docs.

Unsubscribing from this thread. Good luck to ya.

**Comment by pursehouse** [comment]
Spark only works with Casher. So if I want to use.. AuthorizeNet or FirstDate or whatever... because of the short sighted structure of Cashier, it means rewriting Spark myself to support other gateways.

**Comment by sayhicoelho** [comment]
Neither Stripe or Braintree are supported here in my country. 👎

**Comment by Adrion** [comment]
Damn each time I'm looking for a laravel functionnality I found a 13 years old or locked threads...
What a community... 😕 

I'm also sad to see how fast the idea was rejected.
I will find a proper alternative, thanks for the package though. 👍

**Comment by robclancy** [comment]
@Adrion this is what I read

"Damn each time I want someone to do something for me I find it isn't done for me! Why doesn't Laravel create the entire website for me??!! What a joke of a community".

**Comment by pursehouse** [comment]
@robclancy you are a really bitchy child...

**Comment by robclancy** [comment]
Oh the conspiracy theorist is back :D

**Comment by moazam1** [comment]
Darn, time is flying! I feel like I started this conversation few weeks ago!

**Comment by driesvints** [comment]
We won't be reconsidering PayPal in this library sorry. There's now cashier-mollie library which you might want to look into. It has PayPal support.

**Comment by kevosomi** [comment]
> We won't be reconsidering PayPal in this library sorry. There's now cashier-mollie library which you might want to look into. It has PayPal support.

@driesvints: Last time we checked you are not @taylorotwell so just stop answering questions not directed to you and hogging all the questions. Thank you!

**Comment by kevosomi** [comment]
> @taylorotwell I was wondering if you would reconsider you choice not to support PayPal. The initial decision looks like it was made a few years ago and I would find it very useful. I am about to embark on using a different system because of it but I would be happy to put my efforts into extending Cashier instead.

Try https://packagist.org/packages/angelleye/paypal-php-library 

According to their website and PayPal, Angell EYE is a certified PayPal developer, official PayPal partner, 3-time star developer award winner, and a PayPal Ambassador.

**Comment by robclancy** [comment]
@kevosomi he works for Taylor you idiot.

**Comment by kevosomi** [comment]
@robclancy Then he should probably call himself @taylorotwell coz that's the person the question was directed to. Try to learn how to read and understand statements it will alienate stupidity and introduce enlightenment.

**Comment by robclancy** [comment]
This issue really does seem to attract morons.

**Comment by kevosomi** [comment]
@robclancy Yes Captain Moron.
