### ISSUE TITLE
Better coupon support & promotion codes

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier-stripe#852]
Add some better APIs to work with coupons on subscriptions, etc so people don't need to do this themselves with the Stripe SDK. Add a specific Coupon object.

Things to consider: 

- Coupon object
- Validate coupons
- Retrieve coupon code from subscriptions
- Update coupon code on subscriptions

**Comment by driesvints** [comment]
Also add the ability to update coupons on a subscription.

**Comment by ReckeDJ** [comment]
Don't forget the (new) Promotion Codes feature!
https://stripe.com/docs/billing/subscriptions/discounts/codes

**Comment by driesvints** [comment]
@ReckeDJ been looking into that today a bit as part of #1007. Think we can add some simple methods for that as well.

**Comment by driesvints** [comment]
I already sent in a small PR in advance for this: https://github.com/laravel/cashier-stripe/pull/1032

**Comment by pierrocknroll** [comment]
Hi @driesvints 
It could be great to have a method to send a promotion or a coupon with his "code", not his id.

**Comment by driesvints** [comment]
@pierrocknroll that's not possible with Stripe. You can only pass an ID with their API: https://stripe.com/docs/api/subscriptions/create

**Comment by pierrocknroll** [comment]
Yeah, totally, but it could be cool to have a method via Cashier like this :
```
    public function withPromotionCodeName($promotionCode)
    {
            $codes = \Stripe\PromotionCode::all([
                'active' => true,
                'code' => $promotionCode,
                'limit' => 1,

            ]);
            if ($codes->count()) {
                $this->withPromotionCode($codes->first()->id);
            }
     }
```

**Comment by driesvints** [comment]
I'm not sure that needs to go into Cashier that's user-land code to me. You can map those out in a config in a similar fashion like you do in Spark.

**Comment by tomphilpotts** [comment]
@driesvints 

There is a issue using withPromotionCode.

The current documentation simple says: 

```
$user->newSubscription('default', 'price_monthly')
     ->withPromotionCode('promo_code')
     ->create($paymentMethod);
```

This is however a little misleading because if a user currently adds the user facing code  for example '50OFF', this would fail. Because Stripe is looking for the 'promo_xxxxx' code. 

This is a issue that I have run into currently. There is disconnect between the code that a user would use at checkout and the one that Stripe requires to process the payment.

I am currently running this query to retrieve the promotion code ID:

```
    public function getStripePromotionCode($user_supplied_code)
    {
       return collect(Cashier::stripe()->promotionCodes->all()->data)
            ->firstWhere('code', $user_supplied_code);
    }
```

I am validating the code before processing the payment. 

Hope this helps.

Tom
